"""extend vacancy fields

Revision ID: 66f5957cd436
Revises: d1b17e512727
Create Date: 2026-06-26 12:07:06.211535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f5957cd436'
down_revision: Union[str, None] = 'd1b17e512727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('salary', sa.String(length=100), nullable=True))
    op.add_column('vacancies', sa.Column('experience', sa.String(length=100), nullable=True))
    op.add_column('vacancies', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'description')
    op.drop_column('vacancies', 'experience')
    op.drop_column('vacancies', 'salary')
    # ### end Alembic commands ###
