"""add search_keyword to user

Revision ID: 74a6f628b445
Revises: 827be5687252
Create Date: 2026-06-24 14:28:48.372857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a6f628b445'
down_revision: Union[str, None] = '827be5687252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_keyword', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'search_keyword')
    # ### end Alembic commands ###
